### ISSUE TITLE
Docs error on website

### ISSUE THREAD

**Issue by nic-avant** [temporalio/temporal-learning#269]
https://learn.temporal.io/getting_started/python/first_program_in_python/#workflow-definition

At this link the note below the code references `MoneyTransferWorkflow` but if I understand it right that should just be `MoneyTransfer` or the code should be updated to match the referenced class name

**Comment by fairlydurable** [comment]
EDU-2696 PR https://github.com/temporalio/temporal-learning/pull/271

**Comment by fairlydurable** [comment]
@nic-avant Thank you for the great ticket. This kind of feedback really helps us.
